### ISSUE TITLE
Volume Level 0 to  128?

### ISSUE THREAD

**Issue by bastianbeggel** [Gronis/pykef#1]
I was wondering why you use 128 as the scaling factor for the volume?
My understanding was that the LS 50 expect a volume level between 0 and 100.
BTW. HA expect volums in the rage of 0 to 1. 

Line 65 (" volume = int(self.__volume) % 128 + 128") looks strange. Why do you have to add 128?

Then, I think it is not safe to implement def volume in Line 56 the way you did. 
Maybe the user has changed the volume by other means and the internal variable is not up to date. Can that happen?

**Comment by Gronis** [comment]
I will update so that 0-100 is used. 

Line 65: If volume is set to None (mute) Then the unmuted volume is retained (eg. the old value + 128). If it was muted and set to mute, nothing change.

Line 56: The idea is to use listeners so that when something change on the speakers, the change will get reported back. Maybe I can use getVolume for now when no listeners are implemented.

**Comment by Gronis** [comment]
Also, how does hass handle mute? Should I use None as volume as I do now?

**Comment by beggel-hs-kl** [comment]
I looked at some implementations and documentation.
e.g.
https://developers.home-assistant.io/docs/en/creating_platform_example_light.html
and 
https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/media_player/nad.py

The way I understand this at the moment is that there are no listeners. But there needs to be an update function that HA can call to tell the components to update their internal state (e.g. by querying the speakers).  

I would like the internal lib to do not keep track of the current state but to just query the speaker. 
Thus, getVolume should always query the speaker. I will implement the update function in the HA wrapper. I will keep an internal state as in the NAD example. 

I think mute is a true/ false flag. Volume if mute is on? Do not know right now. None is fine at the moment.

**Comment by Gronis** [comment]
Ok, I will make the component stateless and each time the user requests a value (e.g volume), it will query the speaker.

There is a problem with keeping the connection alive. It seams that only one client can be connected at a time. This means that the connection must be closed after not being used for a while.

I'm trying out using a thread that automatically disconnects the speakers if no requests has been made for x secs (3 secs atm). Is this OK?

**Comment by Gronis** [comment]
It's probably easier to keep track of the state from this component, since it has to connect and disconnect to the speakers continuously.

**Comment by bastianbeggel** [comment]
> Ok, I will make the component stateless and each time the user requests a value (e.g volume), it will query the speaker.
> 
> There is a problem with keeping the connection alive. It seams that only one client can be connected at a time. This means that the connection must be closed after not being used for a while.
> 
> I'm trying out using a thread that automatically disconnects the speakers if no requests has been made for x secs (3 secs atm). Is this OK?

WTF. Only one connection at a time? That is bad. I was not expecting this. 
At the beginning I opened a new connection for each command. But this was really slow and also produced a lot of errors. 

The 3 sec rule seems to make sense. But I am no expert either. Lets just give it a try.

**Comment by bastianbeggel** [comment]
Thanks for all your effort.

**Comment by Gronis** [comment]
> WTF. Only one connection at a time? That is bad. I was not expecting this.
> At the beginning I opened a new connection for each command. But this was really slow and also produced a lot of errors.
> 
> The 3 sec rule seems to make sense. But I am no expert either. Lets just give it a try.
I know, it is really bad x)

The reason it fails when connecting is that the app also does this and if both connect at the same time, it fails. I tried to get around this by retrying and catching exceptions, while tuning a wait timer which increases each time it fails. 

I decreased it to 1 sec for now, I guess we want as low as possible, but not to low so that it disconnect during one transaction (for example when fetching many values in a sequence). Test it out. The timeout can be tweeked by setting the `_CONNECTION_KEEP_ALIVE` constant at the top.

> Thanks for all your effort.

No problem :)

**Comment by chimpy** [comment]
@bastianbeggel Just in case the question is still on your mind:

LS50 does only take vol from 0-100 however it calculates mute by taking that value and adding 128 to it. So mute is all "volume levels" from 128 to 228. And you unmute by setting the volume to (muted-vol-value - 128).

**Comment by Gronis** [comment]
What happens if you set it to something between 100 and 128? Is that mute or 100% volume?

**Comment by chimpy** [comment]
From memory it's 100%. But if you query afterwards, it will report 127 for example. It doesn't limit and transform it to 100.

I will double check this after work.

**Comment by Gronis** [comment]
I think we can close this one.
