### ISSUE TITLE
Automatic reconnect

### ISSUE THREAD

**Issue by bastianbeggel** [Gronis/pykef#2]
I think it is essential to implement the Automatic reconnect. Maybe the KEF is offline when HA starts. 
Before accessing the KEF the code has to check if the connection/ the socket  is still valid and needs to reconnect.

The lib should also have a way to check if the  KEF are powered  up. This way we can communicate to HA (as state) if the Medial Player is available.

**Comment by Gronis** [comment]
Yes. This needs to be implemented :)

**Comment by Gronis** [comment]
Check the latest commit. 

The problem right now is that any command (including initializing the component) when the speakers are offline is a blocking operation. Is this OK for hass, or should it be made async? I believe that a hass component is very easy to make async, so I did not bother with that.

**Comment by bastianbeggel** [comment]
Ok. Thanks for the heads up. 
Yes, components can be easily written using async calls. This is not really much overhead. 
I will look at that on Wednesday.

**Comment by Gronis** [comment]
This is implemented
