### ISSUE TITLE
Works fine with LSX

### ISSUE THREAD

**Issue by vanne** [Gronis/pykef#4]
Hi,

I tested pykef with my LSX and it works flawlessly.
Apart from the USB input source which the LSX does not have.
Also the maximum volume that was set is respected.

Will try to add turnOn() in the upcoming days.

**Comment by vanne** [comment]
I sniffed the sequences produced by the 4 input source buttons in the KEF Control app, only to find out that I didn't really have to: when switching input source with the current `pykef`, the LSX speakers are turned on if needed. (Network is still up and running when speakers are off, no real WoL needed.)

Anyway, for reference, here are the sequences that are sent when pressing the source buttons when speakers are OFF, powering them ON to the selected source:

```
$ echo -ne '\x53\x30\x81\x02\xb0' | nc -c 192.168.10.123 50001 # Wake up to LAN
$ echo -ne '\x53\x30\x81\x09\x9f' | nc -c 192.168.10.123 50001 # Wake up to Bluetooth
$ echo -ne '\x53\x30\x81\x0b\x32' | nc -c 192.168.10.123 50001 # Wake up to Opt
$ echo -ne '\x53\x30\x81\x0a\xa9' | nc -c 192.168.10.123 50001 # Wake up to Aux
```

When speakers are ON, the same sequences can be used to switch between sources.

When pressing the active input source button a different sequence is sent and the speakers are powered off. Each of the buttons produces its own sequence but sending any of them with netcat works, no matter what the active source is.

power off sequences:
```
53308182bb
5330818994
5330818b39
5330818aa2
```


Feel free to close this issue.

**Comment by Gronis** [comment]
Hi! Thanks for testing pykef with LSX. Good to know that it is working, and that power on already works without further implementation.
