### ISSUE TITLE
Another maintainer

### ISSUE THREAD

**Issue by Gronis** [Gronis/pykef#5]
I have recently sold off my KEF LS50W speaker and because of this, I will probably not maintain this repository. If someone wants to maintain this repository, please write here.

**Comment by basnijholt** [comment]
You could mention [`aiokef`](https://github.com/basnijholt/aiokef) in the `README.md`, which is build from `pykef` but has 99% of the code rewritten, is more fully-featured, and async.

I plan to maintain it as long as I have KEF speakers (and maybe even later) 😄

**Comment by Gronis** [comment]
I have linked to your repository. Thanks for your contributions :) Glad you picked up the project.
